FROM node:22-alpine AS dependency-base

# Create destination directory
ENV WORKDIR=/home/attendance_api
WORKDIR $WORKDIR

# Install system dependencies
RUN apk add --no-cache mysql-client bash vim git wget curl nodejs npm && \
    rm -rf /var/cache/apk/* && \
    rm -rf /var/lib/apt/lists/* /tmp/*

# Install NestJS CLI
RUN npm install -g @nestjs/cli@10

FROM dependency-base AS server_development

# Set NODE_ENV environment variable to development
ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

# Copy over package.json and package-lock.json files
COPY ./sources/attendance_api/package*.json $WORKDIR/

# Cài đặt các phụ thuộc Node.js
RUN npm install

# Sao chép mã nguồn vào container
COPY ./sources/attendance_api/ $WORKDIR/

# Điều chỉnh quyền
RUN chmod -R 755 $WORKDIR

# Mở cổng 3001
EXPOSE 3001

# Lệnh chạy ứng dụng
CMD ["npm", "run", "start:dev"]
